name: CI status
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * 0'
    
jobs:
  testDockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Test Docker image
        run: |
         echo "Building docker image............."
         docker build . -t hello-go:test
         echo "Running docker image.............."
         docker run --rtm hello-go:test  
  
      - name: Build Notification
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "Github Bot"
          SLACK_MSG_AUTHOR: ${{ github.actor }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Dockerfile failure :boom:'
          SLACK_TITLE: ${{ github.event.repository.name }}
          SLACK_ICON: https://avatars.githubusercontent.com/${{ github.actor }}?size=48   
