name: CI status
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  testDocerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Test Docker image
        run: |
         echo "Building docker image............."
         docker build . -t hello-go:test
         echo "Running docker image.............."
         docker run --rm hello-go:test  
